# Generated by Django 5.1.7 on 2025-03-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.reg_form_ch')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foodpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.reg_form_us')),
            ],
        ),
    ]
