# Generated by Django 5.1.7 on 2025-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_orders_razorpay_order_id_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
