# Generated by Django 5.1.7 on 2025-03-13 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
