# Generated by Django 5.1.7 on 2025-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_foodpost_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='created_at',
        ),
    ]
