# Generated by Django 5.1.7 on 2025-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_foodpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='utype',
            field=models.CharField(choices=[('user', 'User'), ('chef', 'Chef'), ('admin', 'Admin')], max_length=50),
        ),
    ]
